# Inserts a blank line between shell prompts
add_newline = false
command_timeout = 10000

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\n\
$character
"""

[directory]
style = "#F8BD96"

[git_branch]
style = "#C6AAE8"

[git_state]
style = "#EBDDAA"

[character]
success_symbol = "[󰘧](bold green)"
error_symbol = "[󰘧](bold red)"
